title: Ako rozšírená realita zmení náš každodenný život
baseURL: https://quizzical-tesla-fb2f40.netlify.com/
languageCode: cs-cz
publishDir: public

menu:
  main:
    - name: Domů
      url: /
      weight: 10
    - name: Archiv
      identifier: post
      url: /post/
      weight: 20

params:
  description: Description of my new site.
  authors: Autoři

