title: Rozšírená realita
baseURL: https://quizzical-tesla-fb2f40.netlify.com/
languageCode: cs-cz
publishDir: public

menu:
  main:
    - name: Homepage
      url: /
      weight: 10
    - name: Archive
      identifier: post
      url: /post/
      weight: 20

params:
  description: Ako rozšírená realita zmení náš každodenný život
  authors: Authors

